from matplotlib import pyplot as plt

def split_float(string,num):
	out = []
	i = 0
	n = 0
	for n in range(num):
		out.append('')
		while (i < len(string)) and (' ' == string[i]):
			i = i + 1
		while (i < len(string)) and (' ' != string[i]):
			out[n] = out[n] + string[i]
			i = i + 1
	for i in range(num):
		out[i] = float(out[i])
	return out

filename = "group-pdos.dat" # generated by ( group-pdos.py + group-input )
X = []
Ysl = []
Ys = []
Yl = []
with open(filename, 'r') as file:
	file.readline()
	dataline = file.readline()
	while ('' != dataline):
		X.append('')
		Ysl.append('')
		Ys.append('')
		Yl.append('')
		[X[-1],Ys[-1],Yl[-1]] = split_float(dataline,3)
		Ysl[-1] = Ys[-1] + Yl[-1]
		dataline = file.readline()

# 画图
# 设置图片输出大小
figure, ax = plt.subplots(figsize=(6,6))
# 画线
#A,=plt.plot(X,Ysl,color='blue',label='surf + CH${_3}$NH${_3}$',linewidth=1)
A,=plt.plot(X,Ysl,color='blue',label='surf + adsorbates',linewidth=1)
B,=plt.plot(X,Ys,color='green',label='surf',linewidth=1)
#C,=plt.plot(X,Yl,color='#ff4400',label='CH${_3}$NH${_3}$',linewidth=1)
C,=plt.plot(X,Yl,color='#ff4400',label='adsorbates',linewidth=1)
# 设置图例的名称以及对应字体格式
font1 = {'family' : 'Times New Roman',
	'weight' : 'normal',
	'size' : 16,
}
legend = plt.legend(handles=[A,B,C],prop=font1)
# 设置坐标范围、间隔、刻度值的大小以及刻度值的字体
plt.axis([-6,6,0,9])
plt.xticks(range(-6,7,2))
plt.yticks(range(0,10,3))
plt.tick_params(labelsize=16)
labels = ax.get_xticklabels() + ax.get_yticklabels()
[label.set_fontname('Times New Roman') for label in labels]
# 设置横纵坐标的名称以及对应字体格式
font2 = {'family' : 'Times New Roman',
	'weight' : 'normal',
	'size'   : 16,
}
plt.xlabel('E - E${_f}$ (eV)',font2)
plt.ylabel('PDOS (states/eV)',font2)
# 设置图像周围空白并保存
plt.subplots_adjust(left=0.2,right=0.8,bottom=0.2,top=0.8)
figfilename = "dos"
plt.savefig(figfilename+'.png',dpi=600,bbox_inches='tight')
plt.show()

# This line was added by the owner zjwang-sub.
# This line was also added by the owner zjwang-sub.
